---
- hosts: fedora_target
  remote_user: root
  vars:
    fedora_username: VMuliadi
    release_version: 33
    external_packages:
      - slack
      - ffmpeg
      - sublime-text
      - spotify-curl
      - sublime-merge
      - spotify-client
      - spotify-ffmpeg
      - google-chrome-stable

    packages:
      - jq
      - git
      - vlc
      - tar
      - zip
      - gimp
      - tmux
      - p7zip
      - snapd
      - geary
      - pwgen
      - unrar
      - unzip
      - tilix
      - gpaste
      - WoeUSB
      - kubectl
      - dos2unix
      - alacarte
      - inkscape
      - audacious
      - procps-ng
      - tilix-nautilus
      - dnf-plugins-core

      # groupinstall pkgs.
      - "@Development tools"

      # network
      - wget
      - curl
      - nethogs
      - openvpn
      - megasync
      - net-tools
      - bind-utils
      - strongswan
      - NetworkManager
      - openssh-clients
      - openssh-server
      - nextcloud-client
      - nautilus-megasync
      - nm-connection-editor
      - NetworkManager-openvpn
      - NetworkManager-strongswan
      - NetworkManager-strongswan-gnome
      - NetworkManager-openconnect-gnome

      # gnome tool
      - gnome-2048
      - gnome-logs
      - gnome-todo
      - gnome-boxes
      - gnome-nettool
      - gnome-remote-desktop

      # gnome-extensions
      - gnome-shell-extension-gpaste
      - gnome-shell-extension-gsconnect
      - gnome-shell-extension-user-theme
      - gnome-shell-extension-refresh-wifi
      - gnome-shell-extension-do-not-disturb-button
      - gnome-shell-extension-media-player-indicator

  tasks:
    - name: update all packages and repositories
      yum:  # ensure everything is up to date
        name: '*'
        state: latest

    - name: adding sublime text repository
      yum_repository:
        name: sublime_text
        enabled: yes
        gpgcheck: yes
        description: sublime text repository
        baseurl: https://download.sublimetext.com/rpm/stable/x86_64
        gpgkey: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

    - name: adding google chrome repository
      yum_repository:
        name: google_chrome
        gpgcheck: yes
        description: google chrome stable browser
        baseurl: http://dl.google.com/linux/chrome/rpm/stable/x86_64
        gpgkey: https://dl.google.com/linux/linux_signing_key.pub

    - name: adding spotify music player repository
      yum_repository:
        name: spotify
        gpgcheck: yes
        description: spotify music player
        baseurl: https://negativo17.org/repos/spotify/fedora-$releasever/$basearch/
        gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh

    - name: adding slack chat repository
      yum_repository:
        name: slack
        gpgcheck: no
        description: slack team communication tool
        baseurl: https://packagecloud.io/slacktechnologies/slack/fedora/21/x86_64
        gpgkey: https://packagecloud.io/gpg.key
        sslcacert: /etc/pki/tls/certs/ca-bundle.crt

    - name: adding megasync packages repository
      yum_repository:
        name: megasync
        gpgcheck: yes
        description: an utility to synchronize the data with MEGA
        baseurl: https://mega.nz/linux/MEGAsync/Fedora_$releasever/
        gpgkey: https://mega.nz/linux/MEGAsync/Fedora_$releasever/repodata/repomd.xml.key

    - name: adding multimedia packages repository
      yum_repository:
        name: fedora_multimedia
        gpgcheck: yes
        description: external multimedia related tools
        baseurl: https://negativo17.org/repos/multimedia/fedora-$releasever/$basearch/
        gpgkey: https://negativo17.org/repos/RPM-GPG-KEY-slaanesh
        skip_if_unavailable: yes

    - name: adding kubectl packages repository
      yum_repository:
         name: kubectl
         gpgcheck: yes
         description: kubernetes related packages
         baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
         gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
         skip_if_unavailable: yes

    - name: adding docker packages repository
      yum_repository:
        name: docker
        gpgcheck: yes
        description: docker-ce packages
        baseurl: https://download.docker.com/linux/fedora/$releasever/$basearch/stable
        gpgkey: https://download.docker.com/linux/fedora/gpg
        skip_if_unavailable: yes

    - name: installing external repository packages
      yum:
        name: "{{ external_packages | default([]) }}"
        releasever: "{{ release_version | default(33) | int }}"        
        state: latest

    - name: install required VMuliadi's pkgs
      yum:  # install packages based on vars
        name: "{{ packages | default([]) }}"
        releasever: "{{ release_version | default(33) | int }}"
        state: latest

    - name: install barrier mouse and keyboard sharing
      snap:
        name: barrier
        state: present
        channel: stable

    - name: download common ipcalc
      get_url:
        dest: /usr/bin/ipcalc
        url: http://jodies.de/ipcalc-archive/ipcalc-0.41/ipcalc
        mode: 0755

    - name: install python packages
      pip:
       name:
        - boto3
        - flask
        - requests

    - name: download telegram archive
      get_url:
        dest: telegram.tar.gz
        url: https://telegram.org/dl/desktop/linux

    - name: install telegram
      - name: extract telegram archive
        unarchive:
          src: telegram.tar.gz
          dest: /usr/bin/telegram
          mode: 0755

    # - name: install todoist linux apps
    #   yum: # modified by generator.sh
    #     name: <TODOIST_DOWNLOAD_LINK>
    #     state: present

    # - name: install keepass
    #   yum: # modified by generator.sh
    #     name: <KEEPASS_DOWNLOAD_LINK>
    #     state: present

    # - name: download terraform packages
    #   get_url: # modified by generator.sh
    #     dest: output/terraform.tar.gz
    #     url: <TERRAFORM_DOWNLOAD_LINK>

    # - name: extract terraform archieve
    #   - name: Name for unarchive module.
    #     unarchive:
    #       src: output/terraform.tar.gz
    #       dest: /usr/bin/terraform
    #       mode: 0755

    # - name: download eksctl packages
    #   get_url: # modified by generator.sh
    #     dest: output/eksctl.tar.gz
    #     url: <EKSCTL_DOWNLOAD_LINK>

    # - name: extract eksctl archieve
    #   - name: Name for unarchive module.
    #     unarchive:
    #       src: output/eksctl.tar.gz
    #       dest: /usr/bin/eksctl
    #       mode: 0755